language: python
python: 2.7
install: pip install -U -rrequirements_dev.txt
script:
- tox -e ${TOXENV}
- codecov
env:
  matrix:
  - TOXENV=py27
  - TOXENV=flake8
  - TOXENV=cov
  global:
  - secure: "EnyelU+0H1RkShIaWPd5k+6WwE6THJ0Nmlp0TMCnJ6hvMG5ElKz43VPFSadTWZKKBirG031N+TDO9mfkN+araJ3Et74idWfGFJkTJxPx0pfy/pXD1BZeMsE3xhSjrfXEWv1AGAlwJboTdlHs0Qo62JSn2gmG/bfVX66f+o6m1ex7NnWQgmg4n64vMiDza+3nStuKCu1WeBWisneHuh5DX+C3DNmJLoehCYcbu675uPdrCePQxjMK2FAyYZYlfNdGKbqQK4UD8ZvubudJrSrEDuGrvsCvg4ZqXnjIvMRhIhv1ctd1EUO1eG0ID/RycapUV7MmSgdPoNHFV/JY3Ct+nSlA4lzb0vnJr+e1sajPk6j+NEKxgANx/assXvFXH3NvxUfC5yLmi4g/JnvnjE/UkwPicUh0Y8UiRfIh78aJcmZ7hYO1a0Wop4hkIg7ENUe8zWs4dMmBnq8jT0Vx08Hu6mx68bWj7g8+yTgiH/AIQA+cBKnGAyKlbB9Mf6C5+rDuNpFqLQ367CYg9IEdSmtVq3sPyj7rz5IIWMGmfyx6ZiRPepBvLje193Qoo79XKNh7taLDINRpGvbzzqDi6EfahThx77QKf0HP5MxWWOHpLi5PO1hvf44HKSU8rLEbwZ8nzBmh7ZRk7ijegyUZSl0E1lucMdTOlTBqR1kH3G8f4aE="
  - secure: "tHQW1Xc4BhsXi2LsoGhVn2bZMdSswVcDnVOWyRuIWWScHbr+QnEga9aI7JMNZofw23UTkq+sIKyxlmkku1UNWgBO+Cr+lAdfi2C+N7xdVEQG/lWL+kUTtApa2whZ0MZ7xkzNY2pz8B4VZNV5OwcrpsPvrblU6RFZg3qspbGdN9GbDhh0wo/P6LBjqUTm0fKi1hW2PYvTiEB9ILS9pGa+of3vzSUqz2ZfEwIsGJsPxuZlBJ6EjyYgGzaTeLs11eKd7rr0P9RrV9JcyKCATloK5k1st8AZEF0qKv8vNok1uERqFCQ6jfTcqXs1sPHm3Ga+rzHR75l2zJUxjVWZKujnG3sWTfVp+TeROuQ2W3EaMxZLfO6rXoW/c5cByYnFTSpzgqlt3PxCW9hR21r/XpqcWAkw41yeIRXo92gC4svlOEk+K663jMncETxgi47WNAUGzuxhkMwkP2C7GP0FmpXZwFNAOE9guItgrbOul/QWO/MQgFgo7vbptN74fq9JZ3ftW+1yzl5oBe4o1HxbENsLqB0IfNhlclfUCPdTId+x9vHBixYOG4ZOikcoLFMHAgC4ZcLT5JtOtRBSL0R9KZNvufoN5ZN0WzVogDRDFJDBgdsfmaE9tB7DIaB75LO/B8OT9ae6mPWSl004ac3aK1WZvZPUpThhVBVVS3rVg2Ll3B4="
deploy:
  on:
    condition: "$TOXENV == py27"
    repo: twindb/twindb_infrastructure
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: ipJtZdfMtfUaD2W794Ukf2ZehmA880uPz2DMt7tL4VHoB+b514HgbdzheH0Azg04Ucqn/+g57OFtCg4kdkGCxHad8m+hfrnJKug+1CEttRFsFrpflJErnYdc+459X3s3utixxKXlKebv3vtg9VFoYXq7rA5Z5WM3ukshtP2sCK/OsgYEleFHYBIRtjnZy9Ip/IFLeBz4vhZaEkwAUSNW3/BWDCBZTC7EfmBVWDsd1gHLSZn94Ib0lCD4npSWf5y/yv6XrTrSX0ElA2gotNJpWWeb2q85oTAlFETGUolIUUUB4QpZobswB7TWp1R7GD+pPFquuzePPq5ybrp4r8qN1m13C9DZ79oH89ndalpb1ACjqb8F53/xNa8BG318m6p9rSP3xIUI8SBqU/T4QiSGa2f/DZCABEXnkhn3CXNhN1Uho76tWVO9SXOmPavhZ89FF3nqEZewD2udjhepN2+Yax8X6K3DiWPxrVJxJi4no2zZiu6tMITjlTfEy++sKuP5rSOAo5JUSSBGfu5BkSI3MbtLGqx+sJo/6A3PDkj68besrnsMMCNOKTqtYfVDBz76m1f2xZ+z/yWina7nw3O9wTNuCKR9FbVEdy48Hg0O3mGYw400+GynYMqiAigoZvDhNdvFr/Qs0PEmSUpwOwnLYUACwU6cNBW9wEgtHV3rsYs=
  provider: pypi
  user: twindb

before_install:
- openssl aes-256-cbc -K $encrypted_b5d684c3f7a3_key -iv $encrypted_b5d684c3f7a3_iv -in deployer.key.enc -out ~/.ssh/id_rsa -d
