language: python
python: 2.7
install: pip install -U -rrequirements_dev.txt
script:
- tox -e ${TOXENV}
- codecov
env:
  matrix:
  - TOXENV=py27
  - TOXENV=flake8
  - TOXENV=cov
  global:
  - secure: Qf3j7X+eJ1eDberiRFKh7ly5zIWer5Y4sc8fUye4PNIvdSgwQ+7V0DVVn4Ka7ZuambyqXVQc8sa3gPO6loEazzmIWV3qaLjMYcqUNcZoCRlthk2/ph8wi9ytWCV1zY4AiksPe5LuapdmLfySu9R5DdumobcaWFP6iy6ZwovR2e7f0PbYi1jHKEKiCrrps9eIpPpB/tlIoT4m/Iw61OufZz+PWSLs6fd5aeudiuqAClJQXhN7kFOTEgqGBp0CG42EbfG08Qf9KMDPeqIe31+C8gvYMTsV9gtFfc4ty1ejn+8IVaNNiNj/3vEa2pqWeJDmX+fQFX9dvMAjxG8oB742EwEdI2RHwDsIsPao8s1QQ0Ib8qKu16Pbg1PM4WNxNPOVBJkuOj/7gV8T7i9+vXk0jAc9WW0B8XvhGrH3EMx9x78xQ3GaMHLBQwdN6/NRMpEGDhDnnxzhkJWyKZNRZIqHFlIc6lr70q6nwP1jWPn9QfsPKRhTUhO0s8UjFHdv2zKbT5JtxQN+u9efZHq3gdNxp/xleBhm2A6m2Fx1sYar1xAgMNDuPu1BSodwxptqU2tUd5NnOVVEeX58sunyPKE7n5KL2ytLFZJXZzdO/exeAOLyBMpfN0nnuGsywTT1ze6d0OeMcXozlTes2W+pKsuzOM2/ZAfk4Rhl8zDEu2fjXgI=
  - secure: PkNNwittxd75gR8aZUlrgc3CnKqfhagwQtUyi0VliRJFljWm2LNv/D063lWoHWKYXw57YtjqfRlQH7vX78+mWMot0GaiFP3BM/MBhAPqjXAqPY0Bm1XOItVL3oMSkYq24L1fiyXyUr8Vbu8VnH9hbSF+qk+zPcmUSwKWM5zPbszuC304j1N9QGo6d+fSzmJBaBDhxkdPLxkspPs9FwGwOcC7W25towjhItZG8oN2naRcvGHFJ9YHaRld1aDbSQUXtknz5wHoUx1RObmKd/3UwTN7sudShBF7M2CH1jckbp3ibi8GwuyzEDBKhckJNDl9cNmsJDOUihm/C9m2r3bG17Bg7bD2gYfA5If7b+HkFrgtRYIhZG3VG1WOBP3kFA411jznTYFwqEQvogmaeYWAaAZdXM0kjlpAS+mFgLK02WRZQAb9olohd5PBpl0UeXJaanKNiJ+w2aAvhC7WDDMuqzU7SXX6jv0KYCVLSRulPtK+6jeHgPzIi6q8IH5U2VMuq/34KhGOCVJWJzzdeKexGsNt1AHmUj9rndU5ig4QHS5t1C3b1tHbaX04W8ywupe/Y9vnjgCtXclfS+XtC8nXHOwLyxW9wqu3Dv4JQKM+M/7HQE+y27Hy4ueyWE1hrwFEas0vH1DuB/BsVZK9yZ1tJU9L1g8qsxHm3bgqNWnghrw=
  - secure: DV4Nug2+/DVu+cBgO+M1Na5E/l/CSSZaCSOSC4Gu7zrSZHrCvxZ2taVhukYsD6BjL5U9Mm1XTqu5vMB2EvCTP1w0o2ZBEI0M1V06D35KMFOErSdLYU1TrI4/CauUSwg/ankgY22K9/OWfmnEJrCkPMmoVfhvPqbDQpk7tHwF/88wuSFbv3YU9YYFrCWFmkXZx9lGbLvZac24tTP3Oe2mC+gKgVFta7uB1V/jnwyGOs4HUunWBEr08PAMP0NHdJ9s6ZI+XRbRKEMjTx6C4COOwKfVcb3UZCwbhV375a71OjurtyRqOOP9QwVzv4iO5NUF/BSRLowCxAXAGMN5cn+jPEqHf2byM6u4oNwzIwv0Qzy4jPXzIwvbHCuAr8FOxvHdSdXDtUDyrH3QdsoMTQ0s84b2qwNjuu4iYtNlE96mZIQmnLEwu2UgE2RfRZyA1lSPycggOniaDcwWJdl/ifrymEXaJC6GgOgf2WDdG+9j1nxzrmBUtgHUrBewfErywLCtOVCnHb58NmPIigpDzC7THdnoo45J4VpogUqpisa7GK/kmIsaMStN5I1yHgmb6bSNyZfhbkwafdC3kdVkfMfH8oIDThe5QatnIvQcbhfcKrAiGk4dJHn7SSh1Nf0W6BAWkAR6KKqpIsz1Gv9+dMkeLAtxc8vP/lwAU5u/WC8ujTQ=
deploy:
  on:
    condition: "$TOXENV == py27"
    repo: twindb/twindb_infrastructure
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: ipJtZdfMtfUaD2W794Ukf2ZehmA880uPz2DMt7tL4VHoB+b514HgbdzheH0Azg04Ucqn/+g57OFtCg4kdkGCxHad8m+hfrnJKug+1CEttRFsFrpflJErnYdc+459X3s3utixxKXlKebv3vtg9VFoYXq7rA5Z5WM3ukshtP2sCK/OsgYEleFHYBIRtjnZy9Ip/IFLeBz4vhZaEkwAUSNW3/BWDCBZTC7EfmBVWDsd1gHLSZn94Ib0lCD4npSWf5y/yv6XrTrSX0ElA2gotNJpWWeb2q85oTAlFETGUolIUUUB4QpZobswB7TWp1R7GD+pPFquuzePPq5ybrp4r8qN1m13C9DZ79oH89ndalpb1ACjqb8F53/xNa8BG318m6p9rSP3xIUI8SBqU/T4QiSGa2f/DZCABEXnkhn3CXNhN1Uho76tWVO9SXOmPavhZ89FF3nqEZewD2udjhepN2+Yax8X6K3DiWPxrVJxJi4no2zZiu6tMITjlTfEy++sKuP5rSOAo5JUSSBGfu5BkSI3MbtLGqx+sJo/6A3PDkj68besrnsMMCNOKTqtYfVDBz76m1f2xZ+z/yWina7nw3O9wTNuCKR9FbVEdy48Hg0O3mGYw400+GynYMqiAigoZvDhNdvFr/Qs0PEmSUpwOwnLYUACwU6cNBW9wEgtHV3rsYs=
  provider: pypi
  user: twindb

before_install:
- openssl aes-256-cbc -K $encrypted_b5d684c3f7a3_key -iv $encrypted_b5d684c3f7a3_iv -in deployer.key.enc -out ~/.ssh/id_rsa -d
