language: python
python: 2.7
install: pip install -U -rrequirements_dev.txt
script:
- if [ -z "$AWS_SECRET_ACCESS_KEY" ] then echo "not defined" else echo "defined" fi
- tox -e ${TOXENV}
- codecov
env:
  matrix:
  - TOXENV=py27
  - TOXENV=flake8
  - TOXENV=cov
deploy:
  on:
    condition: "$TOXENV == py27"
    repo: twindb/twindb_infrastructure
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: ipJtZdfMtfUaD2W794Ukf2ZehmA880uPz2DMt7tL4VHoB+b514HgbdzheH0Azg04Ucqn/+g57OFtCg4kdkGCxHad8m+hfrnJKug+1CEttRFsFrpflJErnYdc+459X3s3utixxKXlKebv3vtg9VFoYXq7rA5Z5WM3ukshtP2sCK/OsgYEleFHYBIRtjnZy9Ip/IFLeBz4vhZaEkwAUSNW3/BWDCBZTC7EfmBVWDsd1gHLSZn94Ib0lCD4npSWf5y/yv6XrTrSX0ElA2gotNJpWWeb2q85oTAlFETGUolIUUUB4QpZobswB7TWp1R7GD+pPFquuzePPq5ybrp4r8qN1m13C9DZ79oH89ndalpb1ACjqb8F53/xNa8BG318m6p9rSP3xIUI8SBqU/T4QiSGa2f/DZCABEXnkhn3CXNhN1Uho76tWVO9SXOmPavhZ89FF3nqEZewD2udjhepN2+Yax8X6K3DiWPxrVJxJi4no2zZiu6tMITjlTfEy++sKuP5rSOAo5JUSSBGfu5BkSI3MbtLGqx+sJo/6A3PDkj68besrnsMMCNOKTqtYfVDBz76m1f2xZ+z/yWina7nw3O9wTNuCKR9FbVEdy48Hg0O3mGYw400+GynYMqiAigoZvDhNdvFr/Qs0PEmSUpwOwnLYUACwU6cNBW9wEgtHV3rsYs=
  provider: pypi
  user: twindb

before_install:
- openssl aes-256-cbc -K $encrypted_b5d684c3f7a3_key -iv $encrypted_b5d684c3f7a3_iv -in deployer.key.enc -out ~/.ssh/id_rsa -d
