language: python
python: 2.7

install: pip install -U -rrequirements_dev.txt

script:
  - tox -e ${TOXENV}
  - codecov

env:
    matrix:
        - TOXENV=py27
        - TOXENV=flake8
        - TOXENV=cov
    global:
        - secure: "Xof0yYp8NGr35kVGa7FKqo6chE6grV6dlEk7yoxQpi9ueqb9oOx6gRpYH/qyH1xxrp9xYRGoKb6vV42/QDD+u/Z3kQbcAJPvxmakn9ZQWziE4wcEm9xJBdGZrxyaFeQwj2PkFjNXs4ydsdb45BnGhs2BErno69OxVHHhI5eZKol4nuIcxhWD9wky9OVBy4BevFo4qOQKO8mPa+1V2mAiMxh/vcfUjG37qnCF1Tppa8vqOF2l9z3ZL4Bv3Cx63Z1H3QN3w9PnpvIcjxyFwq6TS1YouQJO0xJZJwstkqMvSDe8i33Ephc6bxXZn6H3h3QjZS3Vpxa5l5WvfHxnMGpL0EawNDar6bjS9HdoLPCbgdSrfQVCVih+dDvs9bghkM35PT6ffzLfhiagp26aM6lBHeWtbDdztbdAdzRk605Olwhcj4uRBFneBCVbbhwxUxgsWTjXLuEAsIuUCLXf2b5gsOSMMWZqNHnUHQR5xfH1mjWrKbWkLmbOqRgWF11izd5YUAceD3671y46n+oGkrPuvTB8iYgaeImVDaxEtgEFPG8+Vd+EOqxW6aeqYAbckcLYQYIrSOnZ2I+9Pt76ZN4TuWIhJXDIP5ObZ4S74t3yHOHK2L0/k0EU6Q+X0t/FlBW4dpZxUJtD9IFLBeo9awpV16cfXR+UK/Xfq5g4SU7TqFI="
        - secure: "sQOiBT6jV+gT3naKWX7PcIv3g59RWcM0xi6wiLUToi1pZ/DzK6C4CQWksA2f0N4g9lbIPaOOwBnmJtxhiGNb8aheu8BV3Uwb83WMoIijm9El18EADZruvOPThjTH51Wdrb8g8dvlM9EhGcwm85ZZ7dbkXLuZ/0Ro4X0RZHgmTlTjuf3D0asgoNcM1SLDro8EwKJ6PTqNhPPjC99mlO5ZSAXfme6AbW5gDRg3caymIqLBmST1UrgXg6FDG+ZtKS80FtGnPl/+8rSU/6D14XyUq5CrH65H2zWPOgduXnc/TptJAvyf/lCrkcIrgoH6ESNcMuoNOG5S6F1X3GIju91j3sLrZHuNJFzxyux/26iajURk6DQ+yKDgO6FdKt8klR90Xw3Q4KzePrziuTfF5rzPiuWSITW5vCDJryoRmPSKZB+oYtsmJZZhjWEFjyIq3ia0xlMbJS37+0wlkECJtSjVrGQ9Fn28lR1NOqmbg1VWBMHbDpERhiOhhEwzAph6AaHT7a/QPgJakFDTo0Z84OHgr/rU8UAIgvMGfTL8fXlQSNNXxc9WAVwhPNSrMwJ0NJ5a25CGKreQEh7Ua7TvRyslW6tBQ59dQ3pw1+YdGVck5yC3oxfhTiUy+OhxjFmZbJiH9l9Kd2Nr3O+ssPyaBiz6NpQvR07ZCJCXNbjXOr3h0As="
        - secure: "hq03RiOG+nW/9dLRs2BX03esH/PDCoLI2pCyCn0wsjHuyzmtjqGFqD1CsKYK7+75FN7kcDlpv/fIiTULvefTPixDBsVB/GGYBO4LMbUUht1hGl6noDPs237RgEoB/WAFXjE03TdhYmCpAhJuvpm0BqK95dw7Ir6ri4M73XX7sgFaWglpWUfbO3rfipsyLIwyomqgtsGEKM9fbRixV+axQc+FpPDWxaMPaLOsAUoLuLh9V6VYCNv44bv1sAIUE0M3U99xNqdxjASMZsFECjbXfR/5cLSm5D32dJzw16DcWIer85TII56pVdU5Dof5eOTRsjcqksTNwde9DRv2zayvN0hiGNAmUyNvjnAhVDt9Rbmghoqe5fIswdkWLl4kzMinctauRIJrc3Cfw0MoRQu0xG65RyoSEqHdZ3aZfO01rYHCcmgtKh8ZZFNsu3D2pLsKS8MxsrT+C+sqIBnfTY4oeOup01JvgG9+5lgjv9NT7tarCW4bQ/JAPDgwHkxEK7IqHEaBy5nJkh8Nsvm03dOiOMf4Pf5pqbhzyr86fpcujw1XiIZ7OIgi8jnFPM1c6M0JO0ZFT0qGgJ4TSB5zcqahzzXQxJHZRpuiA7rBwASr7rmHYZAskLem9n52pfaRhzPKMGTmnEIg8TPbVEJRKzimXLrYP3pMmvzkWP2eg2/0DG8="

deploy:
  true:
    condition: $TOXENV == py27
    repo: twindb/twindb_infrastructure
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: ipJtZdfMtfUaD2W794Ukf2ZehmA880uPz2DMt7tL4VHoB+b514HgbdzheH0Azg04Ucqn/+g57OFtCg4kdkGCxHad8m+hfrnJKug+1CEttRFsFrpflJErnYdc+459X3s3utixxKXlKebv3vtg9VFoYXq7rA5Z5WM3ukshtP2sCK/OsgYEleFHYBIRtjnZy9Ip/IFLeBz4vhZaEkwAUSNW3/BWDCBZTC7EfmBVWDsd1gHLSZn94Ib0lCD4npSWf5y/yv6XrTrSX0ElA2gotNJpWWeb2q85oTAlFETGUolIUUUB4QpZobswB7TWp1R7GD+pPFquuzePPq5ybrp4r8qN1m13C9DZ79oH89ndalpb1ACjqb8F53/xNa8BG318m6p9rSP3xIUI8SBqU/T4QiSGa2f/DZCABEXnkhn3CXNhN1Uho76tWVO9SXOmPavhZ89FF3nqEZewD2udjhepN2+Yax8X6K3DiWPxrVJxJi4no2zZiu6tMITjlTfEy++sKuP5rSOAo5JUSSBGfu5BkSI3MbtLGqx+sJo/6A3PDkj68besrnsMMCNOKTqtYfVDBz76m1f2xZ+z/yWina7nw3O9wTNuCKR9FbVEdy48Hg0O3mGYw400+GynYMqiAigoZvDhNdvFr/Qs0PEmSUpwOwnLYUACwU6cNBW9wEgtHV3rsYs=
  provider: pypi
  user: twindb
