language: python
python: 2.7
install: pip install -U -rrequirements_dev.txt
script:
- tox -e ${TOXENV}
- codecov
env:
  matrix:
  - TOXENV=py27
  - TOXENV=flake8
  - TOXENV=cov
  global:
  - secure: qkhiv7+0UJkAbHwrLkQ1YxG0aWgEmJLlvmYDspKJNvcwfItp5VJ/yUvQey4QgHG8frzFba+13Hkhowo2QKT8KMmskF4eLHbzl456bHeKCE5h6pM7kq8H8UD+i01MCIaMzh2CxUX0rkDy3QOo1c4Ps9Z7YQ00YSIr7HRV5YpvtljQsmnuFfJ9yPTwH6vpfshxB+7Srz5RB3GK3P92cPvghnKCfdu83HcSvnEiNxnOMv0GLQv4NNCPifoym15FMTIqsNMU8WUc3hNjrW8hfoJk80Y4lHKvmKDFYguDs10V+dB7YbiFUaihu0y8O+ksCUMFSqoyNvG2sN7ZYY4gLCvfWCuyW8hQsrxtrZIA5FTLsTOTr+5qN7qiTXFflvTcQThSvVgMBW633dgKL3umv0G9Ik8+S7zCAv7k3YQWk+OU8xjxEvQqsK3v8j6OAtdOlYCAAZ0VQjET+JXQhfsseuK3tAoZHg0Tb0YERotAZRw5DH2aG/P0O1B88DUqeES6KJAnBtzW6EjMGzxf15eVSGJS2p+EZRXv78I93teIpW5rrAVuWrig5ElTHDXlckEBkcuh3fnIr540cJ81eDgC/4l3rD9hrgid1sU8GPgF7VnI/9aYsVJaaAKojOs+P00JwPABdcNpA5q6Osn1FMg5a5d0KcDu+pu9DYQi7LxovqKcrCc=
  - secure: kRbymAgyMHW4PuPuLL+a29KEM3iPfXCRcPbbsnZlTOQMCTfBL7C5L2y5O88t4x2vh0R1ZNFDPO9tOuZ/PmR5f4E3JiMJZP4beQpbNgRGraymdKxAJR/Z7cxp9dKKC9f2uE+WWR7YXfh9QhZawvzfwYl3tKP36tJ9/I1wT5+5+wqxHK8evrKwq5s7WjWon98SeH+7UHbTATjYneYKW92xGy0X1PLQbhar7Zy2nlAJZbjRBS9+663gqfTyoY+SHmjABWkLA1Tj6KkxdzLL+vg8QVQSdEzoBAaqfHLlwjGhE2Y1otJKxHe8mIISL3gK0bwaVCSnVuYlwsAdyf32BwxJiG1lXtaSR2U3ViwhfSaXO6zHbPKNnorfLuaL7WwlmOU4/8AbQMiuvVmsz9CmxHA+zVBw74PrMQNsf4u7YJMU5JtjiGfSVXZ/yTYKOQwp7pWh8mUvtEzFuNqw2VasAQVzSmZZZDy78OvoibhWIRyVLscamcO31z32pQHDtqc3W+3t32cDz0fYrDZMBvL3YC6KyqUvswLLspTS1W1zFeWtDHkbo+2COMftmy96d1/tjrgrzYOnwfBRclIWpLoIIN/c1nrt+G6IXJM0e/F60CCfxqAZiXjF64ySz/HCKmFo0j7/6GPeS4GGPV4D4boAsakQ95646ZhBH+QdLM1Udnyeqtg=
deploy:
  on:
    condition: "$TOXENV == py27"
    repo: twindb/twindb_infrastructure
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: ipJtZdfMtfUaD2W794Ukf2ZehmA880uPz2DMt7tL4VHoB+b514HgbdzheH0Azg04Ucqn/+g57OFtCg4kdkGCxHad8m+hfrnJKug+1CEttRFsFrpflJErnYdc+459X3s3utixxKXlKebv3vtg9VFoYXq7rA5Z5WM3ukshtP2sCK/OsgYEleFHYBIRtjnZy9Ip/IFLeBz4vhZaEkwAUSNW3/BWDCBZTC7EfmBVWDsd1gHLSZn94Ib0lCD4npSWf5y/yv6XrTrSX0ElA2gotNJpWWeb2q85oTAlFETGUolIUUUB4QpZobswB7TWp1R7GD+pPFquuzePPq5ybrp4r8qN1m13C9DZ79oH89ndalpb1ACjqb8F53/xNa8BG318m6p9rSP3xIUI8SBqU/T4QiSGa2f/DZCABEXnkhn3CXNhN1Uho76tWVO9SXOmPavhZ89FF3nqEZewD2udjhepN2+Yax8X6K3DiWPxrVJxJi4no2zZiu6tMITjlTfEy++sKuP5rSOAo5JUSSBGfu5BkSI3MbtLGqx+sJo/6A3PDkj68besrnsMMCNOKTqtYfVDBz76m1f2xZ+z/yWina7nw3O9wTNuCKR9FbVEdy48Hg0O3mGYw400+GynYMqiAigoZvDhNdvFr/Qs0PEmSUpwOwnLYUACwU6cNBW9wEgtHV3rsYs=
  provider: pypi
  user: twindb

before_install:
- openssl aes-256-cbc -K $encrypted_cdc507ca0594_key -iv $encrypted_cdc507ca0594_iv -in deployer.key.enc -out ~/.ssh/id_rsa -d
